// <auto-generated>
// Do not edit this file yourself!
//
// This code was generated by Xenko Shader Mixin Code Generator.
// To generate it yourself, please install Stride.VisualStudio.Package .vsix
// and re-save the associated .xkfx.
// </auto-generated>

using System;
using Stride.Core;
using Stride.Rendering;
using Stride.Graphics;
using Stride.Shaders;
using Stride.Core.Mathematics;
using Buffer = Stride.Graphics.Buffer;

namespace RescueDrone.Effects
{
    internal static partial class ShaderMixins
    {
        internal partial class CustomModelEffect  : IShaderMixinBuilder
        {
            public void Generate(ShaderMixinSource mixin, ShaderMixinContext context)
            {
                context.Mixin(mixin, "XenkoForwardShadingEffect");
                if (context.ChildEffectName == "HeatShimmeringEffect")
                {
                    context.Mixin(mixin, "HeatShimmeringEffect");
                    return;
                }
            }

            [ModuleInitializer]
            internal static void __Initialize__()

            {
                ShaderMixinManager.Register("CustomModelEffect", new CustomModelEffect());
            }
        }
    }
    internal static partial class ShaderMixins
    {
        internal partial class HeatShimmeringEffect  : IShaderMixinBuilder
        {
            public void Generate(ShaderMixinSource mixin, ShaderMixinContext context)
            {
                context.Mixin(mixin, "HeatShimmering");
            }

            [ModuleInitializer]
            internal static void __Initialize__()

            {
                ShaderMixinManager.Register("HeatShimmeringEffect", new HeatShimmeringEffect());
            }
        }
    }
}
